##Import SCAPE and other packages and connect to database.  

##NOTE: sometimes you have to type your password in the notebook server terminal, not here in the notebook (a python2/python3 difference).

In [2]:
import scape.registry as R
import scape.sql as sql
import os,json
from getpass import getuser,getpass

import sqlalchemy
from sqlalchemy import Column, Integer, String, Numeric, DATETIME
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

ImportError: No module named 'scape'

In [7]:
#Prepare the URL with authentication data

pwd = getpass()
myurl = sqlalchemy.engine.url.URL(
    'postgresql',         # SQL backend type
    username='postgres',  # or get_user() if username is the same
    password = pwd,       #  
    host='localhost',     # assuming you're on a workstation
    database='lanldb',    # Name of your LANL database
    port=5432)            # Make sure this matches your database configuration

········

In [8]:
# Create a persistent engine
global engine
engine=sqlalchemy.create_engine( myurl )

In [9]:
def connect(engine):
    """Read the registry file and connect the metadata to the database object"""
    with open('lanldataregistry.json','rt') as f:
        overlay = json.load(f)
    
    tmd={k:sql.SqlDataSource(engine=engine,
                             metadata=R.TableMetadata(v),
                             table=k,
                             description='') for k,v in overlay.items()}
    reg = R.Registry(tmd)
    return reg

In [10]:
registry=connect(engine)

## Examples of of using registry to explore and understand data

In [11]:
#Get one of the data streams
dns=registry['dns']

In [12]:
#inspect the knowledge engineering on it
dns

DataSource('Unknown')

In [1]:
# Select all the data and have a look at it in a pandas dataframe
q1=dns.select().run().dataframe
q1

NameError: name 'dns' is not defined

In [15]:
# Ask SCAPE to return to you only fields that have dimension hosthame
q2=dns.select("hostname").run().dataframe
q2

     resolvedhost   shost
0           C5030   C4653
1          C16712   C5782
2            C419   C1191
3          C22841   C3380
4           C5030   C2436
5           C2109    C161
6            C528   C5642
7          C22841   C3380
8           C1065   C2428
9           C2109   C2428
10           C586   C2428
11           C528   C2428
12          C2109   C2428
13           C706   C5778
14           C457   C2492
15          C2109   C1299
16           C706    C608
17          C1707   C2517
18         C24436  C24436
19         C26743  C26743
20          C1685   C5778
21          C1707   C3198
22          C1685   C5778
23           C706   C1108
24           C457   C2428
25           C457   C2428
26          C1707   C4651
27          C1685   C2428
28          C1685  C18636
29          C1707  C18636
...           ...     ...
1243         C706   C5778
1244         C528   C5778
1245         C706   C4753
1246         C457   C2492
1247         C529   C5919
1248         C529   C5919
1249        C1065   C5919
1250        C1065   C5919
1251        C1707   C2480
1252         C529   C5919
1253         C529   C5919
1254        C1707   C3254
1255         C743   C4254
1256        C1685   C5913
1257         C529   C4515
1258         C612   C5919
1259         C612   C5919
1260        C1707   C3374
1261        C5030   C3238
1262         C706    C806
1263         C606   C3026
1264        C1685   C4254
1265       C22841   C3380
1266        C1944   C1936
1267        C5030   C2459
1268        C5030   C3457
1269         C706   C4271
1270         C457   C2492
1271        C5588   C2320
1272         C457   C2492

[1273 rows x 2 columns]

In [16]:
q1.groupby(["shost"]).size().sort_values()

NameError: name 'q1' is not defined

In [11]:
# Get some quick statistics to find out which host asks a lot of DNS questions in an hour
q1.groupby(["shost"]).size().sort_values(ascending=False)

shost
C3380     133
C5778      80
C2492      74
C5919      69
C5913      46
C23716     25
C768       21
C5875      16
C5917      16
C1191      15
C2428      15
C2303      14
C1936      13
C2320      12
C421       10
C814        9
C608        9
C843        8
C3554       8
C3165       8
C154        7
C2438       7
C3198       7
C1653       7
C831        7
C4291       7
C3026       7
C453        7
C3143       6
C2798       6
         ...
C3254       2
C4215       1
C3714       1
C354        1
C1905       1
C1142       1
C3607       1
C23724      1
C5782       1
C5642       1
C5633       1
C5358       1
C5337       1
C5332       1
C5186       1
C3131       1
C4233       1
C5043       1
C14343      1
C2668       1
C4812       1
C1800       1
C2032       1
C1754       1
C4517       1
C282        1
C2077       1
C2087       1
C2893       1
C15182      1
dtype: int64

In [17]:
# Ask SCAPE to filter to a particular host, figure out what hosts the talkative host is resolving
q3=dns.select().where("hostname=='C3380'").run().dataframe
q3

       id  time  shost resolvedhost
0       3    15  C3380       C22841
1       7    38  C3380       C22841
2      30    76  C3380       C22841
3      38   100  C3380       C22841
4      47   137  C3380       C22841
5      60   162  C3380       C22841
6      72   198  C3380       C22841
7      89   224  C3380       C22841
8     102   259  C3380       C22841
9     110   286  C3380       C22841
10    122   320  C3380       C22841
11    127   348  C3380       C22841
12    144   381  C3380       C22841
13    151   410  C3380       C22841
14    159   442  C3380       C22841
15    166   472  C3380       C22841
16    174   503  C3380       C22841
17    184   534  C3380       C22841
18    191   564  C3380       C22841
19    202   596  C3380       C22841
20    207   625  C3380       C22841
21    218   658  C3380       C22841
22    226   686  C3380       C22841
23    231   720  C3380       C22841
24    240   747  C3380       C22841
25    250   782  C3380       C22841
26    261   808  C3380       C22841
27    272   844  C3380       C22841
28    289   869  C3380       C22841
29    301   906  C3380       C22841
..    ...   ...    ...          ...
103   940  2808  C3380        C2013
104   944  2822  C3380       C22841
105   948  2828  C3380       C22841
106   971  2881  C3380       C22167
107   972  2883  C3380       C22841
108   978  2890  C3380       C22841
109   987  2921  C3380       C22841
110   994  2952  C3380       C22841
111   996  2959  C3380        C5588
112  1009  3005  C3380       C22841
113  1011  3008  C3380       C22529
114  1013  3014  C3380       C22841
115  1029  3066  C3380       C22841
116  1034  3076  C3380       C22841
117  1051  3127  C3380       C22841
118  1053  3138  C3380       C22841
119  1080  3188  C3380       C22841
120  1088  3200  C3380       C22841
121  1111  3221  C3380       C22841
122  1146  3262  C3380       C22841
123  1158  3310  C3380       C22841
124  1164  3324  C3380       C22841
125  1183  3371  C3380       C22841
126  1187  3386  C3380       C22841
127  1198  3432  C3380       C22841
128  1204  3448  C3380       C22841
129  1223  3493  C3380       C22841
130  1226  3510  C3380       C22841
131  1233  3521  C3380       C22841
132  1265  3572  C3380       C22841

[133 rows x 4 columns]

In [18]:
# Wow, lots of the resolutions go to a particular outside host.  Let's count up
q3.groupby(["resolvedhost"]).size().sort_values(ascending=False)

resolvedhost
C22841    120
C2013       2
C798        1
C586        1
C5728       1
C5640       1
C5588       1
C5136       1
C457        1
C25295      1
C25294      1
C22529      1
C22167      1
dtype: int64

In [19]:
#Who else is resolving that host?
q4=dns.select().where("hostname=='C22841'").run().dataframe
q4

       id  time  shost resolvedhost
0       3    15  C3380       C22841
1       7    38  C3380       C22841
2      30    76  C3380       C22841
3      38   100  C3380       C22841
4      47   137  C3380       C22841
5      60   162  C3380       C22841
6      72   198  C3380       C22841
7      89   224  C3380       C22841
8     102   259  C3380       C22841
9     110   286  C3380       C22841
10    122   320  C3380       C22841
11    127   348  C3380       C22841
12    144   381  C3380       C22841
13    151   410  C3380       C22841
14    159   442  C3380       C22841
15    166   472  C3380       C22841
16    174   503  C3380       C22841
17    184   534  C3380       C22841
18    191   564  C3380       C22841
19    202   596  C3380       C22841
20    207   625  C3380       C22841
21    218   658  C3380       C22841
22    226   686  C3380       C22841
23    231   720  C3380       C22841
24    240   747  C3380       C22841
25    250   782  C3380       C22841
26    261   808  C3380       C22841
27    272   844  C3380       C22841
28    289   869  C3380       C22841
29    301   906  C3380       C22841
..    ...   ...    ...          ...
90    911  2700  C3380       C22841
91    913  2704  C3380       C22841
92    926  2761  C3380       C22841
93    927  2766  C3380       C22841
94    944  2822  C3380       C22841
95    948  2828  C3380       C22841
96    972  2883  C3380       C22841
97    978  2890  C3380       C22841
98    987  2921  C3380       C22841
99    994  2952  C3380       C22841
100  1009  3005  C3380       C22841
101  1013  3014  C3380       C22841
102  1029  3066  C3380       C22841
103  1034  3076  C3380       C22841
104  1051  3127  C3380       C22841
105  1053  3138  C3380       C22841
106  1080  3188  C3380       C22841
107  1088  3200  C3380       C22841
108  1111  3221  C3380       C22841
109  1146  3262  C3380       C22841
110  1158  3310  C3380       C22841
111  1164  3324  C3380       C22841
112  1183  3371  C3380       C22841
113  1187  3386  C3380       C22841
114  1198  3432  C3380       C22841
115  1204  3448  C3380       C22841
116  1223  3493  C3380       C22841
117  1226  3510  C3380       C22841
118  1233  3521  C3380       C22841
119  1265  3572  C3380       C22841

[120 rows x 4 columns]

In [20]:
q4.groupby(["shost"]).size().sort_values(ascending=False)
#so I guess nobody else asked for it.

shost
C3380    120
dtype: int64

In [21]:
# Pivot to flows and see if that host is talking to any other internal hosts
flows=registry['flows']

In [22]:
flows.select().where("hostname =='C3380'").run().dataframe

Empty DataFrame
Columns: [id, time, duration, shost, sport, dhost, dport, protocol, pktcount, bytecount]
Index: []

In [23]:
flows.select().where("hostname =='C22841'").run().dataframe

Empty DataFrame
Columns: [id, time, duration, shost, sport, dhost, dport, protocol, pktcount, bytecount]
Index: []

In [17]:
## Hmm, neither one talked at all...  Let's see if there are interesting flows in this
## Actually, no, I'm going to check it in and go to bed...